/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mEArQtQ4JyWhXaBxZ9RV5A
// Component: JkWCbaX3t5xg

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: mEArQtQ4JyWhXaBxZ9RV5A/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: mEArQtQ4JyWhXaBxZ9RV5A/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import "./plasmic.css"; // plasmic-import: mEArQtQ4JyWhXaBxZ9RV5A/projectcss
import sty from "./PlasmicGaranty.module.css"; // plasmic-import: JkWCbaX3t5xg/css

createPlasmicElementProxy;

export type PlasmicGaranty__VariantMembers = {};
export type PlasmicGaranty__VariantsArgs = {};
type VariantPropType = keyof PlasmicGaranty__VariantsArgs;
export const PlasmicGaranty__VariantProps = new Array<VariantPropType>();

export type PlasmicGaranty__ArgsType = {};
type ArgPropType = keyof PlasmicGaranty__ArgsType;
export const PlasmicGaranty__ArgProps = new Array<ArgPropType>();

export type PlasmicGaranty__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  h2?: Flex__<"h2">;
  span?: Flex__<"span">;
};

export interface DefaultGarantyProps {
  className?: string;
}

const $$ = {};

function PlasmicGaranty__RenderFunc(props: {
  variants: PlasmicGaranty__VariantsArgs;
  args: PlasmicGaranty__ArgsType;
  overrides: PlasmicGaranty__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_mEArQtQ4JyWhXaBxZ9RV5A",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <PlasmicImg__
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"133px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"95px"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"auto"}
        loading={"lazy"}
        src={{
          src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCA5NSAxMTMiPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgc3Ryb2tlPSIjRkI2OTAwIiBzdHJva2Utd2lkdGg9IjMiIGQ9Im0zMy4xNjIgMTA2LjczNi03LjMzLTEyLjQ3NWMtLjQ3NC0uNy0xLjE4My0xLjE2NS0yLjAxMS0xLjE2NUg3LjUwNEwyOS40MiA1OS4xMjhsNi43NCAxLjE2NiA1LjIwMyA5LjQ0M2MxLjA2NCAyLjIxNSAzLjY2NSAzLjE0OCA2LjAzIDIuMjE1bDQuOTY2LTIuMjE1IDIuMzY1IDQuMDh6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KICA8cGF0aCBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iI0ZCNjkwMCIgc3Ryb2tlLXdpZHRoPSIzIiBkPSJtNzAuNDk3IDkzLjUyOS03LjYzIDEzLjM0Ni0yNi42ODMtMzguODA3Yy0uMTIzLS4zNjQtLjI0Ni0uNjA3LS40OTItLjg1bC0yLjcwOC00LjczMS44NjItLjM2NCAxMC4wOSA0Ljg1M2MuNzM5LjM2NCAxLjQ3Ny40ODUgMi4yMTUuNDg1IDEuNzIzIDAgMy40NDYtLjg0OSA0LjMwNy0yLjQyNmw1LjUzOC05LjgyOCA3LjM4My0xLjMzNUw4OS41NyA5Mi4zMTVINzIuNTljLS44NjIgMC0xLjcyMy40ODYtMi4wOTMgMS4yMTRaIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KICA8cGF0aCBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iI0ZCNjkwMCIgc3Ryb2tlLXdpZHRoPSIzIiBkPSJNNDcuNzAzIDcyLjY5NCAzNi42ODYgNzguNTVsLTYuMDU2LTEwLjgtMTIuNDc4LS45NDYuODI2LTEyLjMxNEw5IDQ3LjA0M2w3LjQ0Ny05LjkxOC00LjMxMS0xMS41ODYgMTEuNzAzLTQuMzc0IDIuNzI1LTEyLjA0NCAxMi4yNDMgMi41NTlMNDcuNzAzIDNsOC44OTYgOC42OCAxMi4yNDMtMi41NiAyLjcyNSAxMi4wNDVMODMuMjcgMjUuNTRsLTQuMzEgMTEuNTg1IDcuNDQ3IDkuOTE4LTkuOTggNy40NDguODI3IDEyLjMxNC0xMi40NzguOTQ2LTYuMDU2IDEwLjh6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KICA8cGF0aCBzdHJva2U9IiNGQjY5MDAiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLXdpZHRoPSIzIiBkPSJNMzYgNDIuMTg4IDQ1LjE3IDQ5IDU5IDMyIi8+Cjwvc3ZnPgo=",
          fullWidth: 95,
          fullHeight: 113
        }}
      />

      <div className={classNames("all", "__wab_text", sty.text__tcs0V)}>
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <h2
              data-plasmic-name={"h2"}
              data-plasmic-override={overrides.h2}
              className={classNames(
                "all",
                "h2",
                "h2__mEArQ",
                "__wab_text",
                sty.h2
              )}
            >
              {
                "\u0413\u0430\u0440\u0430\u043d\u0442\u0438\u044f \u0438 \u0441\u0435\u0440\u0432\u0438\u0441"
              }
            </h2>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </div>
      <span
        data-plasmic-name={"span"}
        data-plasmic-override={overrides.span}
        className={classNames(
          "all",
          "span",
          "span__mEArQ",
          "__wab_text",
          sty.span
        )}
      >
        {
          "\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f Orange \u043e\u0441\u0443\u0449\u0435\u0441\u0442\u0432\u043b\u044f\u0435\u0442 \u0433\u0430\u0440\u0430\u043d\u0442\u0438\u0439\u043d\u043e\u0435 \u043e\u0431\u0441\u043b\u0443\u0436\u0438\u0432\u0430\u043d\u0438\u0435 \u0441\u0432\u043e\u0435\u0439 \u043f\u0440\u043e\u0434\u0443\u043a\u0446\u0438\u0438 \u043d\u0430 \u0442\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u0438 \u0420\u0424. "
        }
      </span>
      <div className={classNames("all", "__wab_text", sty.text__n56Ss)}>
        {
          "\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435 \u043e \u0433\u0430\u0440\u0430\u043d\u0442\u0438\u0438"
        }
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "h2", "span"],
  img: ["img"],
  h2: ["h2"],
  span: ["span"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  h2: "h2";
  span: "span";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGaranty__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGaranty__VariantsArgs;
    args?: PlasmicGaranty__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicGaranty__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicGaranty__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicGaranty__ArgProps,
          internalVariantPropNames: PlasmicGaranty__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGaranty__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGaranty";
  } else {
    func.displayName = `PlasmicGaranty.${nodeName}`;
  }
  return func;
}

export const PlasmicGaranty = Object.assign(
  // Top-level PlasmicGaranty renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    h2: makeNodeComponent("h2"),
    span: makeNodeComponent("span"),

    // Metadata about props expected for PlasmicGaranty
    internalVariantProps: PlasmicGaranty__VariantProps,
    internalArgProps: PlasmicGaranty__ArgProps
  }
);

export default PlasmicGaranty;
/* prettier-ignore-end */
