/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mEArQtQ4JyWhXaBxZ9RV5A

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: mEArQtQ4JyWhXaBxZ9RV5A/projectModule

import "./plasmic.css"; // plasmic-import: mEArQtQ4JyWhXaBxZ9RV5A/projectcss

const data = {
  base: `${"plasmic_tokens_mEArQtQ4JyWhXaBxZ9RV5A"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
