// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicGaranty,
  DefaultGarantyProps
} from "./plasmic/blank_project/PlasmicGaranty";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface GarantyProps extends Omit<DefaultGarantyProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultGarantyProps altogether and have
// total control over the props for your component.
export interface GarantyProps extends DefaultGarantyProps { }

function Garanty_(props: GarantyProps, ref: HTMLElementRefOf<"div">) {


  return <PlasmicGaranty root={{ ref }} {...props} />;
}

const Garanty = React.forwardRef(Garanty_);
export default Garanty;
